# Introduction to NumPy

## Instructions:
* Go through the notebook and complete the tasks. 
* Make sure you understand the examples given. If you need help, refer to the documentation links provided or go to the discussion forum. 
* Save your notebooks when you are done.

Note that we use the import keyword to import modules and libraries in Python. You can find out more about this <a href="https://docs.python.org/3/tutorial/modules.html">here</a>.




In [34]:
import numpy as np

## 1 NumPy arrays

NumPy n-dimensional arrays (referred to as ndarrays are a fundamental structure for ML in Python.

### 1.1 Usage examples

To create a NumPy array from list:

    data1D = [6, 7, 8]
    data1DnD = np.array(data1D)
    print(data1D)
    print(data1DnD)

To print useful properties of our array:

    print(data1DnD.shape)
    print(data1DnD.ndim)
    print(data1DnD.dtype)

To change the type of elements:

    data1DnD_float = data1DnD.astype(np.float)
    data1DnD_string = data1DnD.astype(np.string_)

For array indexing:

    print(a[0])   #return the first element of ndarray a
    print(a[:])   #return all the elements of ndarray a
    print(a[-1])  #return the last element of ndarray a
    print(a[:-1]) #return everything up to the last element
    print(a[:-2]) #return everything up to the second last element
    print(a[-2])  #return the second last element

There are various ways of creating an ndarray:

    a = np.array([1, 2, 3])
    b = np.zeros((1,5))              # Create an array of all zeros
    c = np.ones((1,5))               # Create an array of all ones
    d = np.full((1,5), 7)            # Create an array filled with value 7
    e = np.random.random((1,4))      # Create an array filled with random values
    f = np.eye(3)                    # Create a 3x3 identity matrix (2D array)
    g = np.ones((3,3,3))             # 3-Dimensional array

As the name suggests, an n-dimensional array can be generalised to multiple dimensions:

    A=np.array([ [1,2], [3,4] ])     # Create a 2-D array (Matrix)
    print(A[0,1])                    # return the element on first column, second row (0,1)=2
                                     # array indexing works as above

We can reshape a vector (for example, ```v=[v1,v2,…,vN]```) to a matrix of ```N1 x N2``` dimensions (where ```N1xN2 = N```). This is particularly useful for plotting images.  As an example using numpy’s reshape method:

    A = np.array([1,2,3,4,5,6])  # a 1D array 
    B = np.reshape( A, [2,3] ) # reshape as a 2D array with 2 rows and 3 columns
    print(B)
 
**Task 1:**
Go through the examples above, pasting the code given in the empty cell below and verifying the results. 
Make sure you understand what this basic code does. You can find some NumPy documentation <a href="http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html">here</a>.

In [35]:
data1D = [6, 7, 8]
data1DnD = np.array(data1D)
print("data1D:", data1D, "data1DnD:", data1DnD)

print("\ndata1DnD stats")
print("shape:", data1DnD.shape)
print("ndim:", data1DnD.ndim)
print("dtype:", data1DnD.dtype)

data1DnD_float = data1DnD.astype(np.float)
data1DnD_string = data1DnD.astype(np.string_)
print("\ndata1DnD_float:", data1DnD_float, "\ndata1DnD_string:", data1DnD_string)

a = np.array([1, 2, 3])
b = np.zeros((1,5))              # Create an array of all zeros
c = np.ones((1,5))               # Create an array of all ones
d = np.full((1,5), 7)            # Create an array filled with value 7
e = np.random.random((1,4))      # Create an array filled with random values
f = np.eye(3)                    # Create a 3x3 identity matrix (2D array)
g = np.ones((3,3,3))             # 3-Dimensional array

print()
A = np.array([ [1,2], [3,4] ])   # Create a 2-D array (Matrix)
print("A[0,1]:", A[0,1])         # return first column, second row element
                                 # array indexing works as above

A = np.array([1,2,3,4,5,6])      # a 1D array 
B = np.reshape( A, [2,3] )       # reshape as a 2D array with 2 rows and 3 columns
print("\nA:", A, "\nB:", B)

data1D: [6, 7, 8] data1DnD: [6 7 8]

data1DnD stats
shape: (3,)
ndim: 1
dtype: int32

data1DnD_float: [6. 7. 8.] 
data1DnD_string: [b'6' b'7' b'8']

A[0,1]: 2

A: [1 2 3 4 5 6] 
B: [[1 2 3]
 [4 5 6]]


C:\Users\sbgka\AppData\Local\Temp\ipykernel_17196\1405826278.py:10: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  data1DnD_float = data1DnD.astype(np.float)


**Task 2:**
In the empty cell below, create an np array called ```L``` consisting of 15 random elements.


In [36]:
L = np.random.random((15))
L

array([0.70225369, 0.72709114, 0.90854664, 0.2822421 , 0.82240686,
       0.66243763, 0.35289405, 0.19830312, 0.739248  , 0.65414934,
       0.17335006, 0.61762169, 0.58409614, 0.6392203 , 0.67159592])

**Task 3:**
Reshape the array ```L``` to a matrix ```A``` that has 5 rows and 3 columns. Print the matrix to verify the result.


In [37]:
A = np.reshape(L, [5,3]) # model: L.reshape(5,3)
A

array([[0.70225369, 0.72709114, 0.90854664],
       [0.2822421 , 0.82240686, 0.66243763],
       [0.35289405, 0.19830312, 0.739248  ],
       [0.65414934, 0.17335006, 0.61762169],
       [0.58409614, 0.6392203 , 0.67159592]])

**Task 4:**
Reshape matrix ```A``` to a matrix ```B``` that has 3 rows and 5 columns. Then, print the elements in row 0 and 1 only.


In [38]:
B = A.reshape(3,5)
B[0:2]

array([[0.70225369, 0.72709114, 0.90854664, 0.2822421 , 0.82240686],
       [0.66243763, 0.35289405, 0.19830312, 0.739248  , 0.65414934]])

**Task: 5**
Print all elements of ```B``` that are in row 0 and 2 <b>and</b> column 1.


In [39]:
print("My ans:", B[0,1], B[2,1])
print("\nModel ans:\n", B[[0,2],1])

My ans: 0.7270911398407661 0.6176216900308209

Model ans:
 [0.72709114 0.61762169]


In [40]:
A

array([[0.70225369, 0.72709114, 0.90854664],
       [0.2822421 , 0.82240686, 0.66243763],
       [0.35289405, 0.19830312, 0.739248  ],
       [0.65414934, 0.17335006, 0.61762169],
       [0.58409614, 0.6392203 , 0.67159592]])

**Task 6:**
Print all elements of ```A``` that are in the last row (see the ```[-1]``` notation above) and second to last column.


In [41]:
A[[-1],-2]

array([0.6392203])

**Task 7:**
Given the array ```Y``` below, find all indices in the array that are equal to the value 1. Use the NumPy function where to do that. Your final output should look like this: ```[1, 3, 4, 7]```.
You can find some useful documentation to help you with this <a href="https://numpy.org/doc/stable/reference/generated/numpy.where.html">here</a>.


In [42]:
Y = np.array([0,1,0,1,1,2,0,1,0])

idx = []
for i in range(len(Y)):
    if Y[i] == 1:
        idx.append(i)
idx

# model ans: np.where(Y==1)

[1, 3, 4, 7]

**Task 8:**
Split the array ```Y``` defined above into three arrays by using the NumPy function ```array_split```. Print to verify.
You can find some useful documentation to help you with this <a href="https://numpy.org/doc/stable/reference/generated/numpy.array_split.html">here</a>.


In [43]:
np.array_split(Y, 3)

[array([0, 1, 0]), array([1, 1, 2]), array([0, 1, 0])]

**Task 9:**
Given the array ```D``` defined below, find the indices that sort the array. Use the NumPy function ```argsort``` in order to do so. Subsequently, print the sorted array. 
The final output should look like this: ```[ 0 1 2 5 9 10 20]```.


In [44]:
D = np.array([10,5,2,9,20,0,1])
sorted_indices = np.argsort(D) # order of each number
sorted_D = D[sorted_indices]
sorted_D

array([ 0,  1,  2,  5,  9, 10, 20])

**Task 10:**
Create two random 2x2 matrices ```X``` and ```Y``` (2 rows, 2 columns). Use the NumPy function ```concatenate``` in order to concatenate them and create a matrix ```Z``` that has dimensions 4x2 and a matrix ```W``` that has dimensions 2x4.
You can find some useful documentation to help you with this <a href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.concatenate.html">here</a>.


In [45]:
X, Y = np.random.random((2,2)), np.random.random((2,2))
Z = np.concatenate((X, Y), axis = 0)
W = np.concatenate((X, Y), axis = 1)

print("Z:", Z, "\n\nW:", W)

Z: [[0.85904667 0.69807703]
 [0.81440973 0.45057274]
 [0.67625119 0.88266353]
 [0.18247443 0.36348053]] 

W: [[0.85904667 0.69807703 0.67625119 0.88266353]
 [0.81440973 0.45057274 0.18247443 0.36348053]]


**Task 11:**
Create the same matrices ```Z2=Z``` and ```W2=W``` (where ```Z``` and ```W``` are as defined above), but this time use the NumPy functions ```hstack``` and ```vstack```.

You can find some useful documentation to help you with ```hstack``` <a href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.hstack.html#numpy.hstack">here</a> and ```vstack``` <a href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.vstack.html#numpy.vstack">here</a>.


In [46]:
Z2 = np.vstack((X, Y)) # Z is stacked vertically
W2 = np.hstack((X, Y)) # W is stacked horizontally

print("Z2:", Z2)
print("\nW2:", W2)

Z2: [[0.85904667 0.69807703]
 [0.81440973 0.45057274]
 [0.67625119 0.88266353]
 [0.18247443 0.36348053]]

W2: [[0.85904667 0.69807703 0.67625119 0.88266353]
 [0.81440973 0.45057274 0.18247443 0.36348053]]
